#!/usr/bin/env node
/**
 * Wiki maintenance (rules in docs/wiki.md).
 *
 *   node scripts/wiki.js index    regenerate data/wiki/index.md from page headers (never hand-edit it)
 *   node scripts/wiki.js goals    refresh goal pages from the latest personal financial statement (creates missing ones)
 *   node scripts/wiki.js check    broken links, missing header fields, statuses that don't fit the kind, one-way links
 *                                 exits 1 if anything but one-way links is found
 *
 * WIKI_DIR moves the wiki (for tests).
 */
const fs = require('fs');
const path = require('path');
const { loadWiki, wikiHealth, WIKI_DIR, KINDS, KIND_LABELS } = require('./wiki-queries');

const cmd = process.argv[2];
const CURRENT = new Set(['standing', 'active']);
const clip = (s, n) => (s.length > n ? s.slice(0, n - 1).replace(/\s+\S*$/, '') + '…' : s);

if (cmd === 'index') {
  const { pages } = loadWiki();
  const out = ['# Wiki index', '', `Generated by \`node scripts/wiki.js index\` from page headers. Do not edit by hand. Rules: docs/wiki.md.`, ''];
  for (const kind of [...KINDS, ...new Set(pages.map(p => p.type).filter(t => !KINDS.includes(t)))]) {
    const list = pages.filter(p => p.type === kind);
    if (!list.length) continue;
    if (kind === 'reflection') list.sort((a, b) => b.slug.localeCompare(a.slug));
    else list.sort((a, b) => (CURRENT.has(b.status) - CURRENT.has(a.status)) || b.backlinks.length - a.backlinks.length || (b.updated || '').localeCompare(a.updated || ''));
    out.push(`## ${KIND_LABELS[kind] || kind} (${list.length})`, '');
    for (const p of list) {
      const bits = [p.status || 'no status', p.headline, p.updated && `updated ${p.updated}`].filter(Boolean).join(' · ');
      out.push(`- [${p.title}](${p.path}.md) · ${bits}${p.lead ? `. ${clip(p.lead, 140)}` : ''}`);
    }
    out.push('');
  }
  fs.writeFileSync(path.join(WIKI_DIR, 'index.md'), out.join('\n'));
  console.log(`index.md: ${pages.length} pages`);
} else if (cmd === 'goals') {
  // Goal pages mirror the latest personal financial statement: refresh headline numbers, create missing pages.
  const pfsDir = process.env.PFS_DATA_DIR ? path.resolve(process.env.PFS_DATA_DIR) : path.join(__dirname, '..', 'data', 'pfs');
  const latest = fs.existsSync(pfsDir) && fs.readdirSync(pfsDir).filter(d => /^\d{4}-\d{2}-\d{2}$/.test(d) && fs.existsSync(path.join(pfsDir, d, 'snapshot.json'))).sort().pop();
  if (!latest) { console.log('No statement snapshot yet (run /financial-statement); nothing to refresh.'); process.exit(0); }
  const snap = JSON.parse(fs.readFileSync(path.join(pfsDir, latest, 'snapshot.json'), 'utf8'));
  const { pages } = loadWiki();
  const fmt = n => `$${Math.round(n).toLocaleString('en-US')}`;
  const yaml = v => Array.isArray(v) ? `[${v.join(', ')}]` : /[:#]|^\s|\s$|^[\[{'"]/.test(String(v)) ? JSON.stringify(String(v)) : String(v);
  const slugify = s => s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
  let made = 0, refreshed = 0;
  for (const g of snap.goals || []) {
    const pct = Math.max(0, Math.min(1, g.today.pct || 0));
    const headline = g.type === 'retirement' ? `${Math.round(pct * 100)}% of markets last to 95` : g.type === 'debt' ? g.caption.replace(/ at today's payment$/, '')
      : g.type === 'education' ? `${Math.round(pct * 100)}% by the start${(g.today.text.match(/Short (\$[\d,]+)/) || [])[1] ? ` · ${g.today.text.match(/Short (\$[\d,]+)/)[1]} short` : ''}`
      : `${Math.round(pct * 100)}% · ${g.type === 'emergency' ? g.caption : g.today.text.split('.')[0]}`;
    const block = ['<!-- auto:start -->', `From the personal financial statement of ${latest}.`, '',
      `- **Where it stands:** ${g.today.text}`, `- **When:** ${g.when}`, `- **On track today:** ${g.today.ok ? 'yes' : 'no'}`,
      `- **Monthly to stay on plan:** ${g.action && g.action.monthly ? fmt(g.action.monthly) : 'nothing extra'}`, '<!-- auto:end -->'].join('\n');
    const page = pages.find(p => p.type === 'goal' && p._fm.pfs_goal === g.id);
    const header = { headline, progress: pct.toFixed(2), on_track: g.today.ok ? 'yes' : 'no', updated: latest };
    if (page) {
      const file = path.join(WIKI_DIR, page.path + '.md');
      let text = fs.readFileSync(file, 'utf8');
      const end = text.indexOf('\n---', 3);
      let head = text.slice(0, end), rest = text.slice(end);
      for (const [k, v] of Object.entries(header)) head = new RegExp(`^${k}:.*$`, 'm').test(head) ? head.replace(new RegExp(`^${k}:.*$`, 'm'), `${k}: ${yaml(v)}`) : `${head}\n${k}: ${yaml(v)}`;
      rest = /<!-- auto:start -->[\s\S]*?<!-- auto:end -->/.test(rest) ? rest.replace(/<!-- auto:start -->[\s\S]*?<!-- auto:end -->/, block) : `${rest.trimEnd()}\n\n${block}\n`;
      fs.writeFileSync(file, head + rest); refreshed++;
    } else {
      const slug = slugify(g.label);
      const file = path.join(WIKI_DIR, 'goals', `${slug}.md`);
      if (fs.existsSync(file)) { console.log(`skip ${slug}: a page with that name exists but has no pfs_goal`); continue; }
      const fm = { type: 'goal', status: 'active', title: g.label, short: g.label, topic: 'planning', created: latest, updated: latest,
        tags: ['plan', g.tier, g.type], sources: ['data/pfs/<date>/snapshot.json'], headline, progress: pct.toFixed(2), on_track: g.today.ok ? 'yes' : 'no', pfs_goal: g.id };
      const open = !g.today.ok && g.action && g.action.monthly ? `\n## Open\n\n- [ ] Put ${fmt(g.action.monthly)}/mo toward ${g.short || g.label.toLowerCase()} to get back on plan\n` : '';
      const body = `# ${g.label}\n\n${g.caption || g.today.text}. ${g.tier === 'essential' ? 'An essential goal' : g.tier === 'important' ? 'An important goal' : 'A want'}, ${g.when === 'now' ? 'needed now' : `due ${g.when}`}.\n\n${block}\n${open}`;
      fs.mkdirSync(path.dirname(file), { recursive: true });
      fs.writeFileSync(file, ['---', ...Object.entries(fm).map(([k, v]) => `${k}: ${yaml(v)}`), '---', '', body].join('\n'));
      made++;
    }
  }
  console.log(`goals from ${latest}: ${refreshed} refreshed, ${made} created`);
} else if (cmd === 'check') {
  const h = wikiHealth();
  for (const b of h.broken) console.log(`broken link   ${b.page} → [[${b.link}]]`);
  for (const m of h.missing) console.log(`missing       ${m.page}: ${m.fields.join(', ')}`);
  for (const s of h.badStatus) console.log(`bad status    ${s.page}: ${s.problem}`);
  if (process.argv.includes('--one-way')) for (const o of h.oneWay) console.log(`one-way       ${o.from} → ${o.to}`);
  const hard = h.broken.length + h.missing.length + h.badStatus.length;
  console.log(`\n${hard ? `${hard} problem(s)` : 'No problems'}; ${h.oneWay.length} one-way link(s)${process.argv.includes('--one-way') ? '' : ' (--one-way lists them)'}`);
  process.exit(hard ? 1 : 0);
} else {
  console.log(fs.readFileSync(__filename, 'utf8').split('*/')[0]);
}
